server:
    port: 8081
    
spring:
    application:
        name: service1
    profiles:
        active: default
    cloud:
        config:
            enabled: true
eureka:
    instance:
        preferIpAddress: true
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
    client:
        registerWithEureka: true
        fatchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
        
        
        
        
        
        
        