server:
    port: 8083
    
spring:
    application:
        name: service3
    profiles:
        active: default
    cloud:
        config:
            enabled: true
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fatchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
        
        
        
        
        
        
        